"""change payment status

Revision ID: 89dce99a69d9
Revises: 2e7eda226076
Create Date: 2025-08-04 18:04:47.454831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89dce99a69d9"
down_revision: Union[str, Sequence[str], None] = "2e7eda226076"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sbp_payment",
        "status",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.Enum(
            "CONFIRMED",
            "PENDING",
            "CANCELLED",
            name="sbp_payment_status_enum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    op.drop_column("sbp_payment", "currency")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sbp_payment",
        sa.Column(
            "currency",
            sa.VARCHAR(length=32),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "sbp_payment",
        "status",
        existing_type=sa.Enum(
            "CONFIRMED",
            "PENDING",
            "CANCELLED",
            name="sbp_payment_status_enum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
