"""add Payment

Revision ID: 2e7eda226076
Revises: b3ad74d830f3
Create Date: 2025-07-31 12:20:52.568550

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2e7eda226076"
down_revision: Union[str, Sequence[str], None] = "b3ad74d830f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sbp_payment",
        sa.Column(
            "sbp_payment_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("operation_id", sa.UUID(), nullable=False),
        sa.Column("rub_amount", sa.Integer(), nullable=False),
        sa.Column("fee_rub", sa.Integer(), server_default="0", nullable=False),
        sa.Column("total_amount_rub", sa.Integer(), nullable=False),
        sa.Column(
            "crypto_amount", sa.DECIMAL(precision=20, scale=6), nullable=False
        ),
        sa.Column(
            "fee_crypto",
            sa.DECIMAL(precision=20, scale=6),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "total_amount_crypto",
            sa.DECIMAL(precision=20, scale=6),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=32), nullable=False),
        sa.Column(
            "exchange", sa.DECIMAL(precision=20, scale=6), nullable=False
        ),
        sa.Column("sbp_url", sa.Text(), nullable=False),
        sa.Column("outgoing_payment_id", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operation.operation_id"],
            onupdate="CASCADE",
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("sbp_payment_id"),
    )
    op.create_index(
        op.f("ix_sbp_payment_operation_id"),
        "sbp_payment",
        ["operation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sbp_payment_sbp_payment_id"),
        "sbp_payment",
        ["sbp_payment_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_sbp_payment_sbp_payment_id"), table_name="sbp_payment"
    )
    op.drop_index(
        op.f("ix_sbp_payment_operation_id"), table_name="sbp_payment"
    )
    op.drop_table("sbp_payment")
    # ### end Alembic commands ###
