"""init

Revision ID: 3e40f20b6801
Revises:
Create Date: 2025-07-05 22:49:11.969585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e40f20b6801"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column(
            "email_verified",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
        sa.Column("entry_code", sa.CHAR(length=4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(
        op.f("ix_user_telegram_id"), "user", ["telegram_id"], unique=False
    )
    op.create_table(
        "referral",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("referred_by", sa.BigInteger(), nullable=True),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column(
            "active", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["referred_by"],
            ["user.telegram_id"],
            onupdate="CASCADE",
            ondelete="NO ACTION",
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["user.telegram_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("telegram_id"),
        sa.UniqueConstraint("code"),
    )
    op.create_index(
        op.f("ix_referral_referred_by"),
        "referral",
        ["referred_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referral_telegram_id"),
        "referral",
        ["telegram_id"],
        unique=False,
    )
    op.create_table(
        "wallet",
        sa.Column(
            "wallet_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("token", sa.VARCHAR(length=255), nullable=False),
        sa.Column("address", sa.VARCHAR(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "BLOCKED",
                "ARCHIVED",
                name="wallet_status_enum",
                native_enum=False,
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["telegram_id"],
            ["user.telegram_id"],
            onupdate="CASCADE",
            ondelete="NO ACTION",
        ),
        sa.PrimaryKeyConstraint("wallet_id"),
        sa.UniqueConstraint("address"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_wallet_wallet_id"), "wallet", ["wallet_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallet_wallet_id"), table_name="wallet")
    op.drop_table("wallet")
    op.drop_index(op.f("ix_referral_telegram_id"), table_name="referral")
    op.drop_index(op.f("ix_referral_referred_by"), table_name="referral")
    op.drop_table("referral")
    op.drop_index(op.f("ix_user_telegram_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
