"""add referral_operation

Revision ID: 87e894a5b560
Revises: 89dce99a69d9
Create Date: 2025-08-13 16:34:29.069037

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "87e894a5b560"
down_revision: Union[str, Sequence[str], None] = "89dce99a69d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_operation",
        sa.Column(
            "referral_operation_id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("referral_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CONFIRMED",
                "PENDING",
                "CANCELLED",
                name="referral_operation_status_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "operation_type",
            sa.Enum(
                "DEPOSIT",
                "WITHDRAW",
                name="referral_operation_type_enum",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=20, scale=6), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["referral.telegram_id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("referral_operation_id"),
    )
    op.create_index(
        op.f("ix_referral_operation_referral_id"),
        "referral_operation",
        ["referral_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_referral_operation_referral_operation_id"),
        "referral_operation",
        ["referral_operation_id"],
        unique=False,
    )
    op.add_column(
        "referral",
        sa.Column(
            "type",
            sa.Enum(
                "FIXED_INCOME",
                "PERCENTAGE_INCOME",
                name="referral_type_enum",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    op.add_column(
        "referral",
        sa.Column(
            "referral_count", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column(
        "referral",
        sa.Column("balance", sa.Integer(), server_default="0", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("referral", "balance")
    op.drop_column("referral", "referral_count")
    op.drop_column("referral", "type")
    op.drop_index(
        op.f("ix_referral_operation_referral_operation_id"),
        table_name="referral_operation",
    )
    op.drop_index(
        op.f("ix_referral_operation_referral_id"),
        table_name="referral_operation",
    )
    op.drop_table("referral_operation")
    # ### end Alembic commands ###
