"""add referral source

Revision ID: 74b975586598
Revises: 87e894a5b560
Create Date: 2025-11-05 18:51:15.334033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74b975586598"
down_revision: Union[str, Sequence[str], None] = "87e894a5b560"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "referral_operation",
        sa.Column("source_referral_id", sa.BigInteger(), nullable=True),
    )
    op.create_index(
        op.f("ix_referral_operation_source_referral_id"),
        "referral_operation",
        ["source_referral_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "referral_operation",
        "referral",
        ["source_referral_id"],
        ["telegram_id"],
        onupdate="CASCADE",
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "referral_operation", type_="foreignkey")
    op.drop_index(
        op.f("ix_referral_operation_source_referral_id"),
        table_name="referral_operation",
    )
    op.drop_column("referral_operation", "source_referral_id")
    # ### end Alembic commands ###
